# Generated by Django 6.0.6 on 2026-06-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_email_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
