# Generated by Django 6.0.6 on 2026-07-02 17:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paystack", "0004_wallet_created_at_wallet_updated_at_and_more"),
    ]

    operations = [

        migrations.CreateModel(
            name="VariationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=100)),
                (
                    "variation_code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        max_digits=12,
                        decimal_places=2,
                    ),
                ),
                (
                    "fixed_price",
                    models.BooleanField(default=True),
                ),
                (
                    "active",
                    models.BooleanField(default=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
        ),

        migrations.AddField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="phone",
            field=models.CharField(
                max_length=20,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="product_name",
            field=models.CharField(
                max_length=200,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="purchased_code",
            field=models.TextField(
                blank=True,
                default="",
            ),
        ),

        # FIXED
        migrations.AddField(
            model_name="transaction",
            name="request_id",
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="response_code",
            field=models.CharField(
                max_length=10,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="response_description",
            field=models.CharField(
                max_length=255,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="reversed",
            field=models.BooleanField(
                default=False,
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                max_length=100,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="unique_element",
            field=models.CharField(
                max_length=100,
                blank=True,
                default="",
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),

        migrations.AddField(
            model_name="transaction",
            name="wallet_credit_id",
            field=models.CharField(
                max_length=100,
                blank=True,
                default="",
            ),
        ),

        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                max_length=100,
                unique=True,
                blank=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("reversed", "Reversed"),
                ],
                default="pending",
            ),
        ),
    ]