# Generated by Django 6.0.6 on 2026-07-03 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0005_variationcode_transaction_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
