# Generated by Django 6.0.6 on 2026-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0006_alter_transaction_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
