# Generated by Django 6.0.6 on 2026-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0007_alter_transaction_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
