# Generated by Django 6.0.6 on 2026-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0009_alter_transaction_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
