# Generated by Django 6.0.6 on 2026-07-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0010_transaction_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcode',
            name='service_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='paystack.variationcode'),
        ),
        migrations.AddField(
            model_name='variationcode',
            name='service',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
