# Generated by Django 6.0.6 on 2026-07-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0011_remove_variationcode_service_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # Change wallet amount column to balance
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),


        # Change wallet owner ForeignKey to user OneToOneField
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wallet',
                to=settings.AUTH_USER_MODEL,
            ),
        ),


        migrations.RenameField(
            model_name='wallet',
            old_name='owner',
            new_name='user',
        ),


        # Remove old unused transaction field
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_credit_id',
        ),


        # Create Paystack Virtual Account
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'customer_code',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True
                    )
                ),

                (
                    'account_number',
                    models.CharField(
                        max_length=20,
                        unique=True
                    )
                ),

                (
                    'account_name',
                    models.CharField(
                        max_length=200
                    )
                ),

                (
                    'bank_name',
                    models.CharField(
                        max_length=100
                    )
                ),

                (
                    'account_reference',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='virtual_account',
                        to=settings.AUTH_USER_MODEL,
                    )
                ),
            ],
        ),


        # Create Wallet Transaction
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12
                    )
                ),

                (
                    'transaction_type',
                    models.CharField(
                        choices=[
                            ('credit','Credit'),
                            ('debit','Debit')
                        ],
                        max_length=10
                    )
                ),

                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending','Pending'),
                            ('success','Success'),
                            ('failed','Failed')
                        ],
                        default='pending',
                        max_length=20
                    )
                ),

                (
                    'reference',
                    models.CharField(
                        max_length=100,
                        unique=True
                    )
                ),

                (
                    'description',
                    models.CharField(
                        blank=True,
                        max_length=255
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='wallet_transactions',
                        to=settings.AUTH_USER_MODEL,
                    )
                ),
            ],
        ),
    ]